### PR TITLE
Added a DockerFile

### LINKED ISSUE #13: feat: dockerize all the things
## Description

Type: `Feature`

This would give the user a convenient way to run `animego-dl` and `yt-dlp` in an isolated environment.

## Tasks and User Stories

As a user, I would like to:
  * use docker to install node, `animego-dl` & `yt-dlp` in an isolated
    environment
  * be able to mount a directly into the container (so the tool can download to
    the host filesystem).

### PR DESCRIPTION
**Pull request by mayanknoldus**
## Related Issues

#13 

## How To Test It?

**Environment:** `Linux` 
**Node Version:** `v16.13.1` 
**YT-DLP Version:** `2021.12.27` 

**Steps**:

## Checklist

- [X] I have tested on a supported environment: ENTER_ENV_HERE - MacOS?, Linux?
- [X] I have tested using the project's Node version: `v16.13.1`
- [x] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mayanknoldus** [comment]
Hi @vinnyA3 . I have created a DockerFile for the same. Could you please review it and tell me if any changes required. Thankyou.

**Comment by vinnyA3** [comment]
@mayanknoldus Thank you for the PR!  Great work 🎉 

I tested the container, and the necessary dependencies exist; however, there are a few things that should be addressed 🙏🏽 

1 - `yt-dlp` is being installed twice -- instead of using `python` + `pip`, perhaps the manual binary install is fine:
```
RUN wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp 
RUN chmod a+rx /usr/local/bin/yt-dlp 
```

2 - `node` (and npm) are both being installed twice via `nvm` and directly from the deb repos.  For this case, I think it might be better to use the official `node` docker image as a foundation, instead of `python`.
  - currently, the project is using the `gallium` LTS version (`v16.14.1`), so `FROM node:gallium` in Dockerfile should do the trick
  
3 - Since the anime tool is installed from npm inside the container, the `COPY` of the code in the project isn't really necessary

4 - Right now, running the tool, as is, will only download the anime to the container.  Once the user exists the container, the downloaded anime will be lost.  It would be nice to create a `VOLUME` mount point in the [Dockerfile](https://docs.docker.com/storage/volumes/) ... so the user can run the docker container like `docker run -v /username/anime:/app/anime -it animego-dl /bin/bash` -- this will create a mount from the user's host machine, into the container ... ultimately, downloading to the mount point in the container will persist the anime on the host
  - https://docs.docker.com/storage/volumes/ - for more volume information!

----

Please let me know what you think about this!  If you have any questions, or need anything, I am here.  Once again, thank you for the PR 💯

**Comment by mayanknoldus** [comment]
Hi @vinnyA3. Totally agreed with your points. I am on it. Thanks.

**Comment by mayanknoldus** [comment]
Hi @vinnyA3 . I have updated the Dockerfile based on your suggestions. Could you please review the same. Thankyou

**Comment by vinnyA3** [comment]
Awesome @mayanknoldus !  I tested with the volume mount and my target anime was persisted on the host machine.  Here is the command I used: `docker run -v ${PWD}/anime:/anime -it animego-dl /bin/bash`

Once small modification 🙏🏽  and it's good to merge!  There is a cURL request for the `node 14` source (line 7 - `RUN curl -sL https://deb.nodesource.com/setup_14.x`) -- this can be removed; then, it's good to go!

**Comment by vinnyA3** [comment]
@all-contributors please add @mayanknoldus for Pull Request

**Comment by vinnyA3** [comment]
@all-contributors please add @mayanknoldus for code

**Comment by vinnyA3** [comment]
@mayanknoldus Looks good to me ✅  .. Merging now!  I have added your name to the contributors list.  Thank you for your contribution 🎉

**Comment by mayanknoldus** [comment]
@vinnyA3 I have removed the line. I think now its good, didnt know how did i missed that line. And yes it was good working on the issue. Thanks again.

**Comment by vinnyA3** [comment]
> @vinnyA3 I have removed the line. I think now its good, didnt know how did i missed that line. And yes it was good working on the issue. Thanks again.

No worries!  It happens 😄

**Pull request merged**
